name: Build Windows Executable

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [ Debug, Release ]

    runs-on: windows-latest 
    
    env:
      Solution_Name: prepare_msxpico_roms
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x.x


    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Build the application
      run: dotnet build $env:Solution_Name /c $env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
