name: Build Windows Executable

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-latest 
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x.x

    # Build the application
    - name: Build the application
      run: dotnet build prepare_msxpico_roms -c Release

    # Publish the application
    - name: Publish the applications
      run: dotnet publish prepare_msxpico_roms -c Release -o publish
      
    # Upload the application artifacts
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.1.0
      with:
        name: prepare_msxpico_roms
        path: publish        
